[package]
name = "advent_day1"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent_day1"
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "day1"

[dependencies]
advent_common = { path = "../common" }
clap = { version = "4.1.1", features = ["derive"] }
